import type { Metadata } from "next";
import localFont from "next/font/local";
import { Anuphan, Montserrat, Akshar } from "next/font/google";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const montserrat = Montserrat({
  weight: ['500', '700'],
  subsets: ['latin'],
  variable: "--font-montserrat",
});

export const akshar = Akshar({
  weight: ['500', '700'],
  subsets: ['latin'],
  variable: "--font-akshar",
});

export const anuphan = Anuphan({
  weight: ['500', '700'],
  subsets: ['thai'],
  variable: "--font-anuphan",
})

export const metadata: Metadata = {
  title: "Smiley Hours App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} ${akshar.variable} ${anuphan.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
